api_viewer/urls.py
from django.urls import path

from . import views

app_name = 'api_viewer'

urlpatterns = [
    # Home page
    path(
        '',
        views.view_event_types,
        name='event_types'
        ),
    # View events
    path(
        'events/<str:event_type_id>/',
        views.view_events,
        name='events'
        ),
    # View events by comp_id
    path(
        'events_competition/<str:comp_id>/',
        views.view_events_competition_id,
        name='events_competition'
        ),
    # View market book
    path(
        'market_book/<str:market_id>/',
        views.view_market_book,
        name='market_book'
        ),
    # View market info
    path(
        'market_info/<str:market_id>/',
        views.view_market_info,
        name='market_info'
        ),
    # View event info
    path(
        'event_info/<str:event_id>/',
        views.view_event_info,
        name='event_info'
        ),
]

bets/urls.py
from django.urls import path

from . import views

app_name = 'bets'

urlpatterns = [
    # Place a bet
    path(
        'place_bet/<str:id>/',
        views.place_bet,
        name='place_bet'
        ),
    # View all bets
    path(
        'view_bets/',
        views.view_bets,
        name='view_bets'
        ),
    # View settled bets
    path(
        'view_settled_bets/',
        views.view_settled_bets,
        name='view_settled_bets'
        ),
]

django_betfair/urls.py
from django.urls import include
from django.urls import path
from django.contrib import admin

from api_viewer.views import view_event_types

urlpatterns = [
    path(
        '',
        view_event_types,
        name='index'
        ),
    path(
        'admin/',
        admin.site.urls
        ),
    path(
        'api/',
        include('api_viewer.urls')
        ),
]

markets/urls.py
from django.urls import path

from . import views

app_name = 'markets'

urlpatterns = [
    # Add market
    path(
        'add_market/<str:market_id>/',
        views.add_market,
        name='add_market'
        ),
    # View market
    path(
        'view_market/<str:market_id>/',
        views.view_market,
        name='view_market'
        ),
    # Update market
    path(
        'update_market/<str:market_id>/',
        views.update_market,
        name='update_market'
        ),
    # Settle market
    path(
        'settle_market/<str:market_id>/',
        views.settle_market,
        name='settle_market'
        ),
    # View markets
    path(
        'view_markets/<str:sport>/',
        views.view_markets,
        name='view_markets'
        ),
]

api_viewer/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.template.defaulttags import register

from api_viewer.utils import list_event_info
from api_viewer.utils import list_event_types
from api_viewer.utils import list_events
from api_viewer.utils import list_events_competition_id
from api_viewer.utils import list_full_market_info
from api_viewer.utils import list_market_book


@register.filter
def get_item(dictionary, key):
    """ This is a custom filter for django templates allowing you to easily get
    a value from a dictionary."""
    return dictionary.get(key)


def view_event_types(request):
    event_types = list_event_types()
    context = {'event_types': event_types}
    return render(request, 'api_viewer/index.html', context)

def view_events_competition_id(request, comp_id):
    events = list_events_competition_id(comp_id)
    context = {'events': events}
    return render(request, 'api_viewer/events.html', context)

def view_events(request, event_type_id):
    events = list_events(event_type_id)
    context = {'events': events}
    return render(request, 'api_viewer/events.html', context)

def view_event_info(request, event_id):
    event_info = list_event_info(event_id)
    context = {'event_info': event_info}
    return render(request, 'api_viewer/event_info.html', context)

def view_market_info(request, market_id):
    market_info = list_full_market_info(market_id)
    context = {
        'market_info': market_info,
        }
    return render(request, 'api_viewer/market_info.html', context)
    
def view_market_book(request, market_id):
    market_book = list_market_book(market_id)
    context = {
        'market_book': market_book,
        }
    return render(request, 'api_viewer/market_book.html', context)

api_viewer/templates/api_viewer/event_info.html
{% extends "markets/layout.html" %}

{% block content %}

{% for market in event_info %}

<a href="{% url 'api_viewer:market_info' market|get_item:'marketId' %}">Market info for {{ market|get_item:'marketName' }}</a>

{{ market|get_item:'event'|get_item:'name' }}
<br>

{{ market }}<br><br>

{% endfor %}

{% endblock %}

api_viewer/templates/api_viewer/events.html
{% extends "markets/layout.html" %}

{% block content %}

{% for event in events %}

{{ event }}<br>

<a href="{% url 'api_viewer:event_info' event|get_item:'id' %}">Event info for {{ event|get_item:'name' }}</a>

<br>
{% endfor %}

{% endblock %}

api_viewer/templates/api_viewer/index.html
{% extends "markets/layout.html" %}

{% block content %}

<br>
<a href="{% url 'api_viewer:events_competition' 10932509 %}">Premier League</a>
<br>

{% for event_type in event_types %}

<a href="{% url 'api_viewer:events' event_type|get_item:'eventType'|get_item:'id' %}">
{{ event_type|get_item:'eventType'|get_item:'name' }}
</a> - {{ event_type|get_item:'marketCount' }}
<br>

{% endfor %}

{% endblock %}

api_viewer/templates/api_viewer/market_book.html
<br>
{{ market_book }}
<br>

api_viewer/templates/api_viewer/market_info.html
{% extends "markets/layout.html" %}

{% block content %}

{{ market_info }}

<a href="{% url 'api_viewer:market_book' market_info|get_item:'marketId' %}">Market book for {{ market_info|get_item:'marketName' }}</a>
<br>

<a href="{% url 'markets:add_market' market_info|get_item:'marketId' %}">Add market {{ market_info|get_item:'marketName' }}</a>
<br>

{% endblock %}